name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: build image
      run: docker build . -t ruimmarinho/cvserver:latest
    - name: push image to docker hub
      run: |
        docker login -u ruimmarinho -p ${{ secrets.DOCKER_HUB_TOKEN }}
        docker push ruimmarinho/cvserver:latest
