name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: |
          docker login --username ruimarinhoo --password ${{ secrets.DOCKER_GITHUB }} ghcr.io
          docker build . -t ghcr.io/ruimarinhoo/cvserver-backend:latest
          docker push ghcr.io/ruimarinhoo/cvserver-backend:latest
